export const VOTE_OPTION_REQUEST = 'VOTE_OPTION_REQUEST'
export const VOTE_OPTION_SUCCESS = 'VOTE_OPTION_SUCCESS'

export const LOAD_VOTES_REQUEST = 'LOAD_VOTES_REQUEST'
export const LOAD_VOTES_SUCCESS = 'LOAD_VOTES_SUCCESS'

export const LOAD_VOTE_OPTIONS_REQUEST = 'LOAD_VOTE_OPTIONS_REQUEST'
export const LOAD_VOTE_OPTIONS_SUCCESS = 'LOAD_VOTE_OPTIONS_SUCCESS'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const LOAD_USER_VOTES_SUCCESS = 'LOAD_USER_VOTES_SUCCESS'

export const LOGOUT = 'LOGOUT'
export const REMOVE_VOTE_SUCCESS = 'REMOVE_VOTE_SUCCESS'

export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS'
